name: Approve and merge dependabot PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - 'dependabot/**'

permissions:
  pull-requests: write

jobs:
  main:
    name: Approve and merge Dependabot PR
    uses: coopnorge/github-workflow-approve-and-merge-dependabot-pr/.github/workflows/approve-and-merge-dependabot-pr.yaml@main
    secrets:
      reviewbot-github-token: ${{ secrets.REVIEWBOT_GITHUB_TOKEN }}
