on:
  pull_request:
jobs:
  techdocs:
    permissions:
      contents: read
      id-token: write
      packages: read
      pull-requests: read
    name: TechDocs
    uses: coopnorge/github-workflow-techdocs/.github/workflows/techdocs.yaml@v0

  build:
    if: always()
    needs:
      - techdocs
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
        if: |
          needs.techdocs.result == 'failure'
    permissions: {}
